-- Enterprise RBAC layer, on top of the existing owner/admin/member roles:
--
-- 1. Groups: one per user per org (memberships.group_id, not a join table --
--    a user belongs to exactly one group within an organization).
-- 2. group_project_grants: which projects a group can see. An org's
--    owner/admin always sees every project in their own org regardless of
--    group; a plain 'member' sees only what their group is granted.
-- 3. organization_ruleset_grants: which rulesets (rule_folders.ruleset_id) an
--    organization may use at all -- superadmin-controlled.
-- 4. project_ruleset_bindings: which of the org's granted rulesets are
--    actually bound to one project -- owner-controlled. A fresh project has
--    none: "zero bindings unless assigned" is the empty table, not a flag.
--
-- Existing (pre-RBAC) projects and the default organization are backfilled
-- with full access below so today's single-tenant behavior doesn't regress;
-- only *new* organizations/projects start with nothing.

create table if not exists public.groups (
	id bigint generated by default as identity primary key,
	organization_id bigint not null references public.organizations (id) on delete cascade,
	name text not null,
	created_at timestamptz not null default now(),
	constraint groups_org_name_key unique (organization_id, name)
);

create index if not exists groups_organization_id_idx on public.groups (organization_id);

alter table public.memberships
	add column if not exists group_id bigint references public.groups (id) on delete set null;

create index if not exists memberships_group_id_idx on public.memberships (group_id);

create table if not exists public.group_project_grants (
	id bigint generated by default as identity primary key,
	group_id bigint not null references public.groups (id) on delete cascade,
	project_id bigint not null references public.projects (id) on delete cascade,
	created_at timestamptz not null default now(),
	constraint group_project_grants_key unique (group_id, project_id)
);

create index if not exists group_project_grants_project_id_idx on public.group_project_grants (project_id);

create table if not exists public.organization_ruleset_grants (
	id bigint generated by default as identity primary key,
	organization_id bigint not null references public.organizations (id) on delete cascade,
	ruleset_id text not null,
	created_at timestamptz not null default now(),
	constraint organization_ruleset_grants_key unique (organization_id, ruleset_id)
);

create index if not exists organization_ruleset_grants_ruleset_id_idx on public.organization_ruleset_grants (ruleset_id);

create table if not exists public.project_ruleset_bindings (
	id bigint generated by default as identity primary key,
	project_id bigint not null references public.projects (id) on delete cascade,
	ruleset_id text not null,
	created_at timestamptz not null default now(),
	constraint project_ruleset_bindings_key unique (project_id, ruleset_id)
);

create index if not exists project_ruleset_bindings_ruleset_id_idx on public.project_ruleset_bindings (ruleset_id);

alter table public.groups enable row level security;
alter table public.group_project_grants enable row level security;
alter table public.organization_ruleset_grants enable row level security;
alter table public.project_ruleset_bindings enable row level security;

revoke all privileges on table public.groups from anon, authenticated;
revoke all privileges on table public.group_project_grants from anon, authenticated;
revoke all privileges on table public.organization_ruleset_grants from anon, authenticated;
revoke all privileges on table public.project_ruleset_bindings from anon, authenticated;

grant select, insert, update, delete on table public.groups to service_role;
grant select, insert, update, delete on table public.group_project_grants to service_role;
grant select, insert, update, delete on table public.organization_ruleset_grants to service_role;
grant select, insert, update, delete on table public.project_ruleset_bindings to service_role;

revoke usage on sequence public.groups_id_seq from anon, authenticated;
revoke usage on sequence public.group_project_grants_id_seq from anon, authenticated;
revoke usage on sequence public.organization_ruleset_grants_id_seq from anon, authenticated;
revoke usage on sequence public.project_ruleset_bindings_id_seq from anon, authenticated;

grant usage on sequence public.groups_id_seq to service_role;
grant usage on sequence public.group_project_grants_id_seq to service_role;
grant usage on sequence public.organization_ruleset_grants_id_seq to service_role;
grant usage on sequence public.project_ruleset_bindings_id_seq to service_role;

-- Backfill: grandfather the default organization and its pre-RBAC projects
-- into full access to every ruleset that already exists, so existing
-- analysis runs don't suddenly see zero rules. New organizations
-- (Archinova, Aspiring Design 3D) are deliberately left with none.
insert into public.organization_ruleset_grants (organization_id, ruleset_id)
select o.id, rf.ruleset_id
from public.organizations o
cross join public.rule_folders rf
where o.slug = 'default'
on conflict (organization_id, ruleset_id) do nothing;

insert into public.project_ruleset_bindings (project_id, ruleset_id)
select p.id, rf.ruleset_id
from public.projects p
join public.organizations o on o.id = p.organization_id
cross join public.rule_folders rf
where o.slug = 'default'
on conflict (project_id, ruleset_id) do nothing;
