-- Migration: Create public.project_ifc_files
-- Date: 2026-08-30
-- Purpose: Give a project more than one IFC model. public.projects carries a
--          single ifc_file_path, which forces the discipline models of one
--          building (architectural, structural, HVAC, plumbing) into separate
--          projects. This table holds the many; projects.ifc_file_path stays
--          as it is and keeps pointing at the primary model.
--
-- Column types follow the house style set by uploaded_files: a BIGINT identity
-- surrogate key, and a BIGINT project_id, because public.projects.id is BIGINT.
-- Declaring project_id as UUID would make the foreign key unrunnable ("Key
-- columns are of incompatible types") -- the defect corrected in migration 002.
--
-- role is deliberately plain TEXT with no CHECK: the disciplines a model can
-- represent are an open vocabulary ('primary', 'structural', 'architectural',
-- 'context', and whatever a future domain adds), and a CHECK here would turn
-- each new discipline into a schema migration.
--
-- Idempotent: safe to re-run. The backfill is guarded by NOT EXISTS, so a
-- second run inserts nothing rather than duplicating every project's model.
-- Wrapped in a transaction so a failure rolls back cleanly rather than leaving
-- the schema half-migrated.

BEGIN;

CREATE TABLE IF NOT EXISTS public.project_ifc_files (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id   BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    file_path    TEXT NOT NULL,
    file_name    TEXT NOT NULL DEFAULT '',
    is_primary   BOOLEAN NOT NULL DEFAULT FALSE,
    role         TEXT NOT NULL DEFAULT 'context',
    uploaded_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Listing a project's models, and resolving the one model an analysis run
-- starts from. Neither is unique on its own: a project holds many files.
CREATE INDEX IF NOT EXISTS idx_project_ifc_files_project_id
    ON public.project_ifc_files(project_id);
CREATE INDEX IF NOT EXISTS idx_project_ifc_files_project_primary
    ON public.project_ifc_files(project_id, is_primary);

-- A project has at most one primary model. Enforced rather than merely
-- documented, because get_primary_ifc_file() returns one row and a second
-- primary would make which one it returns a matter of row order.
CREATE UNIQUE INDEX IF NOT EXISTS uq_project_ifc_files_one_primary
    ON public.project_ifc_files(project_id)
    WHERE is_primary;

-- Backfill: every project that already has a model gets a row for it, marked
-- primary. projects.ifc_file_path is left in place -- this migration adds a
-- second, richer home for the same fact rather than moving it, so a rollback
-- costs a DROP TABLE and nothing else.
--
-- file_name is the basename of the stored reference (storage refs look like
-- sb://bucket/uploads/ifc/<uuid>_model.ifc). It is recorded as stored rather
-- than prettified: stripping what looks like a uuid prefix would mangle the
-- legitimate name of any model that happens to start with one.
--
-- Windows separators are folded to '/' before the basename is taken, because
-- rows predating object storage hold local paths like C:\models\Tower.ifc. The
-- fold is a plain replace() and the strip a slash-only regex: a bracket class
-- holding a backslash is read as an escape by Postgres ARE and fails with
-- "brackets [] not balanced". The separator is written as an E-string escape
-- so it means one backslash under either setting of standard_conforming_strings.
INSERT INTO public.project_ifc_files (project_id, file_path, file_name, is_primary, role)
SELECT
    p.id,
    p.ifc_file_path,
    regexp_replace(replace(p.ifc_file_path, E'\\', '/'), '^.*/', ''),
    TRUE,
    'primary'
FROM public.projects AS p
WHERE COALESCE(p.ifc_file_path, '') <> ''
  AND NOT EXISTS (
      SELECT 1
      FROM public.project_ifc_files AS f
      WHERE f.project_id = p.id
  );

COMMENT ON TABLE  public.project_ifc_files IS
    'IFC models attached to a project; one row per file, at most one primary';
COMMENT ON COLUMN public.project_ifc_files.project_id IS
    'Foreign key to public.projects.id (BIGINT); rows die with the project';
COMMENT ON COLUMN public.project_ifc_files.file_path IS
    'ObjectStorage reference, e.g. sb://bucket/uploads/ifc/<uuid>_model.ifc';
COMMENT ON COLUMN public.project_ifc_files.file_name IS
    'Basename of the stored reference, for display';
COMMENT ON COLUMN public.project_ifc_files.is_primary IS
    'The model an analysis run starts from; at most one per project';
COMMENT ON COLUMN public.project_ifc_files.role IS
    'Discipline this model carries: primary, structural, architectural, context, ...';

COMMIT;
