create table if not exists public.projects (
	id bigint generated by default as identity primary key,
	name text not null default '',
	description text not null default '',
	status text not null default 'Draft',
	ifc_file_path text not null default '',
	ifc_md5_hash text not null default '',
	created_at text not null default '',
	updated_at text not null default ''
);

create table if not exists public.documents (
	id bigint generated by default as identity primary key,
	md5_hash text not null default '',
	filename text not null default '',
	file_path text not null default '',
	extracted_text text not null default '',
	upload_date text not null default ''
);

create table if not exists public.rules (
	id bigint generated by default as identity primary key,
	reference text not null default '',
	rule_type text not null default '',
	description text not null default '',
	target_ifc_class text not null default '',
	parameters text not null default '{}',
	created_at text not null default '',
	updated_at text not null default '',
	source_text text not null default '',
	property_set text not null default '',
	property_name text not null default '',
	fallback_property text not null default '',
	operator text not null default '',
	check_value text not null default 'null',
	value_min text not null default 'null',
	value_max text not null default 'null',
	unit text not null default '',
	applies_when text not null default '{}',
	severity text not null default 'mandatory',
	keyword text not null default '',
	compliance_type text not null default '',
	exceptions text not null default '[]',
	related_refs text not null default '[]',
	overridden_by text not null default '',
	confidence text not null default '',
	extraction_method text not null default 'manual',
	needs_review integer not null default 0,
	mechanism text not null default '',
	ruleset_id text not null default '',
	rule_category text not null default 'property_check',
	value_min_property text not null default '',
	value_max_property text not null default '',
	value_min_offset text not null default '0',
	value_max_offset text not null default '0'
);

alter table public.projects enable row level security;
alter table public.documents enable row level security;
alter table public.rules enable row level security;

revoke all privileges on table public.projects from anon, authenticated;
revoke all privileges on table public.documents from anon, authenticated;
revoke all privileges on table public.rules from anon, authenticated;

grant select, insert, update, delete on table public.projects to service_role;
grant select, insert, update, delete on table public.documents to service_role;
grant select, insert, update, delete on table public.rules to service_role;

revoke usage on sequence public.projects_id_seq from anon, authenticated;
revoke usage on sequence public.documents_id_seq from anon, authenticated;
revoke usage on sequence public.rules_id_seq from anon, authenticated;

grant usage on sequence public.projects_id_seq to service_role;
grant usage on sequence public.documents_id_seq to service_role;
grant usage on sequence public.rules_id_seq to service_role;