-- Migration: Create public.client_documents table
-- Date: 2026-08-26
-- Purpose: Store project-specific evidence documents (specs, schedules, O&M, assessments, etc.)
--
-- CORRECTED 2026-08-26: project_id was declared UUID, but public.projects.id is
-- BIGINT. The uuid -> bigint foreign key is rejected by Postgres, so the original
-- DDL could not run. project_id is now BIGINT and the surrogate key is a bigint
-- identity, matching public.report_artifacts (id BIGINT, project_id BIGINT).
--
-- Also fixed: to_tsvector('english', tags) is not immutable in an index. Now using
-- to_tsvector('english'::regconfig, COALESCE(tags, '')) which is immutable.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.client_documents (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    filename    TEXT NOT NULL,
    file_path   TEXT NOT NULL,  -- object key in Supabase Storage, e.g. 'client-documents/project-12/spec.pdf'
    file_type   TEXT,           -- MIME type or extension, e.g. 'application/pdf'
    category    TEXT NOT NULL CHECK (category IN (
        'Specification',
        'Schedule',
        'Drawing',
        'O&M Manual',
        'Warranty',
        'Assessment',
        'RFI Log',
        'Other'
    )),
    description TEXT,
    tags        TEXT,           -- comma-separated, e.g. 'corrosion, SS316, pool-area'
    upload_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_client_documents_project_id
    ON public.client_documents(project_id);
CREATE INDEX IF NOT EXISTS idx_client_documents_category
    ON public.client_documents(category);
CREATE INDEX IF NOT EXISTS idx_client_documents_upload_date
    ON public.client_documents(upload_date);

-- Tag search. to_tsvector(regconfig, text) is immutable, so this is index-safe;
-- COALESCE keeps NULL tags from producing a NULL index entry.
CREATE INDEX IF NOT EXISTS idx_client_documents_tags
    ON public.client_documents
    USING GIN (to_tsvector('english'::regconfig, COALESCE(tags, '')));

-- One row per (project, filename): the uploader upserts on this.
CREATE UNIQUE INDEX IF NOT EXISTS idx_client_documents_unique
    ON public.client_documents(project_id, filename);

COMMENT ON TABLE  public.client_documents IS
    'Client-uploaded project documents (specs, schedules, O&M, assessments) used as analysis evidence';
COMMENT ON COLUMN public.client_documents.project_id IS
    'Foreign key to public.projects.id (BIGINT)';
COMMENT ON COLUMN public.client_documents.filename IS 'Original filename of uploaded document';
COMMENT ON COLUMN public.client_documents.file_path IS 'Object key in Supabase Storage';
COMMENT ON COLUMN public.client_documents.file_type IS 'File MIME type or extension';
COMMENT ON COLUMN public.client_documents.category IS
    'Specification, Schedule, Drawing, O&M Manual, Warranty, Assessment, RFI Log, or Other';
COMMENT ON COLUMN public.client_documents.description IS 'User-provided description';
COMMENT ON COLUMN public.client_documents.tags IS 'Comma-separated searchable tags';

-- See the RLS note in migration_002: the app uses the service-role key, which
-- bypasses RLS; enabling it denies anon/authenticated clients by default.
ALTER TABLE public.client_documents ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verify:
--   SELECT column_name, data_type
--     FROM information_schema.columns
--    WHERE table_schema='public' AND table_name='client_documents'
--    ORDER BY ordinal_position;
