-- Multi-tenancy foundation: organizations + memberships, and org_id on projects.
-- Schema only: no RLS policies, no API/auth wiring yet (tracked separately).

create table if not exists public.organizations (
	id bigint generated by default as identity primary key,
	name text not null,
	slug text not null,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint organizations_slug_key unique (slug)
);

create table if not exists public.memberships (
	id bigint generated by default as identity primary key,
	organization_id bigint not null references public.organizations (id) on delete cascade,
	user_id uuid not null references auth.users (id) on delete cascade,
	role text not null default 'member' check (role in ('owner', 'admin', 'member')),
	created_at timestamptz not null default now(),
	constraint memberships_org_user_key unique (organization_id, user_id)
);

create index if not exists memberships_organization_id_idx on public.memberships (organization_id);
create index if not exists memberships_user_id_idx on public.memberships (user_id);

alter table public.organizations enable row level security;
alter table public.memberships enable row level security;

revoke all privileges on table public.organizations from anon, authenticated;
revoke all privileges on table public.memberships from anon, authenticated;

grant select, insert, update, delete on table public.organizations to service_role;
grant select, insert, update, delete on table public.memberships to service_role;

revoke usage on sequence public.organizations_id_seq from anon, authenticated;
revoke usage on sequence public.memberships_id_seq from anon, authenticated;

grant usage on sequence public.organizations_id_seq to service_role;
grant usage on sequence public.memberships_id_seq to service_role;

-- Backfill: give every existing (single-tenant) project a home organization
-- so organization_id can become NOT NULL without breaking existing rows.
insert into public.organizations (name, slug)
select 'Default Organization', 'default'
where not exists (select 1 from public.organizations where slug = 'default');

alter table public.projects
	add column if not exists organization_id bigint references public.organizations (id);

update public.projects
set organization_id = (select id from public.organizations where slug = 'default')
where organization_id is null;

alter table public.projects
	alter column organization_id set not null;

create index if not exists projects_organization_id_idx on public.projects (organization_id);
