-- Migration: Create public.rule_snapshots table
-- Date: 2026-09-02
-- Purpose: Persist named, timestamped, frozen copies of a rule folder's
-- rules at save time, independent of later edits/deletes to the live
-- public.rules / rule-folder rows. Rule folders are mutable, so there was
-- previously no way to keep a durable record of "what rules were actually
-- tested" for later reuse or as a spec sheet handed to a client — this
-- table is the source of truth for that, and for the structured PDF export
-- built on top of it (configuration only, not analysis results).
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.rule_snapshots (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT NOT NULL,
    source_ruleset_id   TEXT NOT NULL DEFAULT '',
    source_mode         TEXT NOT NULL DEFAULT 'manual' CHECK (source_mode IN (
        'pdf', 'ids', 'manual', 'mixed'
    )),
    category            TEXT NOT NULL DEFAULT 'Arch' CHECK (category IN (
        'Arch', 'Piping', 'seismic'
    )),
    rules_json          JSONB NOT NULL DEFAULT '[]'::jsonb,
    rule_count          INTEGER NOT NULL DEFAULT 0,
    notes               TEXT NOT NULL DEFAULT '',
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_rule_snapshots_source_ruleset_id
    ON public.rule_snapshots(source_ruleset_id);
CREATE INDEX IF NOT EXISTS idx_rule_snapshots_created_at
    ON public.rule_snapshots(created_at DESC);

COMMENT ON TABLE  public.rule_snapshots IS
    'Named, timestamped, frozen copies of a rule folder''s rules at save time — independent of subsequent edits to public.rules, and the source for the "configuration only" PDF export.';
COMMENT ON COLUMN public.rule_snapshots.source_ruleset_id IS 'ruleset_id the snapshot was taken from (informational; the live folder may since have changed or been deleted)';
COMMENT ON COLUMN public.rule_snapshots.source_mode IS 'How the snapshotted rules originated: pdf (LLM/regex extraction), ids (IDS import), manual, or mixed';
COMMENT ON COLUMN public.rule_snapshots.rules_json IS 'Frozen JSON array of rule rows (same shape as list_by_ruleset()) captured at snapshot time';
COMMENT ON COLUMN public.rule_snapshots.rule_count IS 'Denormalized count of rules_json entries, for fast list rendering without parsing JSONB';

-- The app uses the service-role key, which bypasses RLS; enabling it denies
-- anon/authenticated clients by default (see client_documents migration).
ALTER TABLE public.rule_snapshots ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verify:
--   SELECT column_name, data_type
--     FROM information_schema.columns
--    WHERE table_schema='public' AND table_name='rule_snapshots'
--    ORDER BY ordinal_position;
