-- Migration: Create public.document_nodes table
-- Date: 2026-09-02
-- Purpose: Persist LlamaIndexIngestor's clause-annotated document nodes for
-- BCF/rule traceability (clause id, page number, parent section, section
-- path). Only nodes that produced at least one deontic statement are
-- expected to be persisted by the application layer, to bound storage
-- growth — this table does not itself enforce that.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.document_nodes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id         BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
    node_id             TEXT NOT NULL,
    text                TEXT NOT NULL,
    clause_id           TEXT,
    page_number         INTEGER,
    parent_section      TEXT,
    section_path        JSONB NOT NULL DEFAULT '[]'::jsonb,
    node_type           TEXT NOT NULL DEFAULT 'paragraph' CHECK (node_type IN (
        'paragraph', 'table', 'list', 'heading'
    )),
    deontic_statements  JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_document_nodes_document_id
    ON public.document_nodes(document_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_document_nodes_unique_node_id
    ON public.document_nodes(document_id, node_id);

COMMENT ON TABLE  public.document_nodes IS
    'LlamaIndex-ingested, clause-annotated document nodes carrying provenance for BCF/rule traceability';
COMMENT ON COLUMN public.document_nodes.document_id IS 'Foreign key to public.documents.id';
COMMENT ON COLUMN public.document_nodes.node_id IS 'LlamaIndexIngestor-assigned node identifier (UUID)';
COMMENT ON COLUMN public.document_nodes.clause_id IS 'Clause/article reference, e.g. 9.8.2.1.(1)';
COMMENT ON COLUMN public.document_nodes.page_number IS '1-based source page number, when known';
COMMENT ON COLUMN public.document_nodes.parent_section IS 'Nearest enclosing section heading';
COMMENT ON COLUMN public.document_nodes.section_path IS 'JSON array breadcrumb of headings, e.g. ["5", "5.3", "5.3.2"]';
COMMENT ON COLUMN public.document_nodes.deontic_statements IS 'JSON array of DeonticStatement objects extracted from this node';

-- The app uses the service-role key, which bypasses RLS; enabling it denies
-- anon/authenticated clients by default (see client_documents migration).
ALTER TABLE public.document_nodes ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verify:
--   SELECT column_name, data_type
--     FROM information_schema.columns
--    WHERE table_schema='public' AND table_name='document_nodes'
--    ORDER BY ordinal_position;
