"""
BIMGUARD AI — BCF Generator Module
Standard: BIM Collaboration Format (BCF) 2.1 — buildingSMART International
Output: BCF-ZIP file containing XML topics, viewpoints, and snapshots
"""

import datetime
import io
import uuid
import zipfile
from dataclasses import dataclass
from xml.sax.saxutils import escape as _escape


@dataclass
class BCFIssue:
    guid: str
    title: str
    description: str
    priority: str  # Critical / Major / Normal / Minor
    status: str  # Active / Open / Info
    assigned_to: str
    due_date: str
    labels: list
    component_guid: str
    component_name: str
    service_type: str
    floor: str
    risk_band: str
    mechanism: str  # galvanic / crevice / combined
    risk_score: float
    mitigation: str
    camera_x: float = 0.0
    camera_y: float = 0.0
    camera_z: float = 5.0
    target_x: float = 0.0
    target_y: float = 0.0
    target_z: float = 0.0


def _utc_now() -> str:
    return datetime.datetime.now(datetime.UTC).isoformat().replace("+00:00", "Z")


def _xml_text(value) -> str:
    """Escape a value for safe inclusion as BCF XML element text content."""
    return _escape(str(value))


def _xml_attr(value) -> str:
    """Escape a value for safe inclusion inside a double-quoted BCF XML attribute."""
    return _escape(str(value), {'"': "&quot;"})


def _markup_xml(issue: BCFIssue, index: int, viewpoint_guid: str) -> str:
    """Generate BCF 2.1 markup.bcf XML for one issue."""
    labels_xml = "\n".join(f"    <Labels>{_xml_text(l)}</Labels>" for l in issue.labels)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<Markup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Topic Guid="{_xml_attr(issue.guid)}" TopicType="Issue" TopicStatus="{_xml_attr(issue.status)}">
    <ReferenceLink></ReferenceLink>
    <Title>{_xml_text(issue.title)}</Title>
    <Priority>{_xml_text(issue.priority)}</Priority>
    <Index>{index}</Index>
    <Labels>
{labels_xml}
    </Labels>
    <CreationDate>{_utc_now()}</CreationDate>
    <CreationAuthor>BIMGUARD AI — GC-001/CC-001 v1.0.0</CreationAuthor>
    <ModifiedDate>{_utc_now()}</ModifiedDate>
    <AssignedTo>{_xml_text(issue.assigned_to)}</AssignedTo>
    <Description>{_xml_text(issue.description)}</Description>
    <DueDate>{issue.due_date}T00:00:00Z</DueDate>
  </Topic>
  <Header>
    <File>
      <Filename>BIMGUARD_AI_Model.ifc</Filename>
    </File>
  </Header>
  <Comment>
    <Guid>{str(uuid.uuid4()).upper()}</Guid>
    <Date>{_utc_now()}</Date>
    <Author>BIMGUARD AI</Author>
    <Comment>{_xml_text(
        "Issue automatically generated by BIMGUARD AI corrosion compliance engine.\n"
        f"Mechanism: {issue.mechanism} | Risk score: {issue.risk_score:.4f} | Band: {issue.risk_band}\n"
        f"Component: {issue.component_name} ({issue.component_guid})\n"
        f"Service type: {issue.service_type} | Floor/zone: {issue.floor}\n"
        f"Mitigation: {issue.mitigation}"
    )}</Comment>
  </Comment>
  <Viewpoints Guid="{_xml_attr(viewpoint_guid)}">
    <Viewpoint>viewpoint.bcfv</Viewpoint>
    <Snapshot>snapshot.png</Snapshot>
    <Index>0</Index>
  </Viewpoints>
</Markup>"""


def _viewpoint_xml(issue: BCFIssue, viewpoint_guid: str) -> str:
    """Generate BCF 2.1 viewpoint.bcfv XML with camera position and component selection."""
    component_guid_attr = _xml_attr(issue.component_guid)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<VisualizationInfo Guid="{_xml_attr(viewpoint_guid)}">
  <Components>
    <Selection>
      <Component IfcGuid="{component_guid_attr}">
        <OriginatingSystem>BIMGUARD AI</OriginatingSystem>
        <AuthoringToolId>{_xml_text(issue.component_guid)}</AuthoringToolId>
      </Component>
    </Selection>
    <Coloring>
      <Color Color="{_risk_colour(issue.risk_band)}">
        <Component IfcGuid="{component_guid_attr}"/>
      </Color>
    </Coloring>
    <Visibility DefaultVisibility="true"/>
  </Components>
  <PerspectiveCamera>
    <CameraViewPoint>
      <X>{issue.camera_x + 5.0}</X>
      <Y>{issue.camera_y - 8.0}</Y>
      <Z>{issue.camera_z + 3.0}</Z>
    </CameraViewPoint>
    <CameraDirection>
      <X>{issue.target_x - issue.camera_x - 5.0}</X>
      <Y>{issue.target_y - issue.camera_y + 8.0}</Y>
      <Z>{issue.target_z - issue.camera_z - 3.0}</Z>
    </CameraDirection>
    <CameraUpVector>
      <X>0</X>
      <Y>0</Y>
      <Z>1</Z>
    </CameraUpVector>
    <FieldOfView>60</FieldOfView>
  </PerspectiveCamera>
</VisualizationInfo>"""


def _risk_colour(band: str) -> str:
    return {
        "LOW": "FF107C10",
        "MEDIUM": "FFFF8C00",
        "HIGH": "FFC05000",
        "CRITICAL": "FFC00000",
    }.get(band, "FF888888")


def _priority_int(priority: str) -> str:
    return {"Critical": "1", "Major": "2", "Normal": "3", "Minor": "4"}.get(priority, "3")


def _placeholder_png() -> bytes:
    """
    Returns a minimal valid 1×1 PNG as a placeholder snapshot.
    In production this would be a rendered viewpoint screenshot from the 3D viewer.
    """
    # Minimal 1×1 red PNG (valid PNG binary)
    import base64

    b64 = (
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+h"
        "HgAHggJ/PchI6QAAAABJRU5ErkJggg=="
    )
    return base64.b64decode(b64)


def generate_bcf(issues: list[BCFIssue], filename: str = "BIMGUARD_AI_Issues.bcf") -> bytes:
    """
    Generates a BCF 2.1 compliant ZIP archive from a list of BCFIssue objects.

    Args:
        issues:   List of BCFIssue dataclass instances
        filename: Output filename (for reference only — returns bytes)

    Returns:
        BCF ZIP file as bytes — write to disk or offer as download
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # BCF version file (required by spec)
        zf.writestr(
            "bcf.version",
            """<?xml version="1.0" encoding="UTF-8"?>
<Version VersionId="2.1" xsi:noNamespaceSchemaLocation="version.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <DetailedVersion>2.1</DetailedVersion>
</Version>""",
        )

        # Project file
        project_guid = str(uuid.uuid4()).upper()
        zf.writestr(
            "project.bcfp",
            f"""<?xml version="1.0" encoding="UTF-8"?>
<ProjectExtension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Project ProjectId="{project_guid}">
    <Name>BIMGUARD AI — Corrosion Compliance Report</Name>
  </Project>
  <ExtensionSchema>extensions.xsd</ExtensionSchema>
</ProjectExtension>""",
        )

        # One folder per issue
        for i, issue in enumerate(issues):
            folder = issue.guid + "/"
            viewpoint_guid = str(uuid.uuid4()).upper()
            zf.writestr(folder + "markup.bcf", _markup_xml(issue, i, viewpoint_guid))
            zf.writestr(folder + "viewpoint.bcfv", _viewpoint_xml(issue, viewpoint_guid))
            zf.writestr(folder + "snapshot.png", _placeholder_png())

    return buf.getvalue()


def issues_from_results(results: list[dict]) -> list[BCFIssue]:
    """
    Converts BIMGUARD AI engine check results into BCFIssue objects.

    Args:
        results: List of dicts from run_compliance_checks()

    Returns:
        List of BCFIssue objects (filtered to Medium risk and above)
    """
    issues = []
    priority_map = {
        "LOW": "Minor",
        "MEDIUM": "Normal",
        "HIGH": "Major",
        "CRITICAL": "Critical",
    }
    status_map = {
        "LOW": "Info",
        "MEDIUM": "Open",
        "HIGH": "Open",
        "CRITICAL": "Active",
    }
    engineer_map = {
        "LOW": "BIM Manager",
        "MEDIUM": "Mechanical / Structural Engineer",
        "HIGH": "Lead Engineer",
        "CRITICAL": "Design Lead + Client Representative",
    }

    for r in results:
        band = r.get("overall_band", "LOW")
        if band == "LOW":
            continue  # Only raise issues for Medium and above

        days = {"MEDIUM": 21, "HIGH": 7, "CRITICAL": 2}.get(band, 21)
        due = (datetime.date.today() + datetime.timedelta(days=days)).isoformat()

        pos = r.get("position", (0, 0, 0))
        mech = r.get("dominant_mechanism", "galvanic")
        score = r.get("overall_score", 0)

        labels = [
            "BIMGUARD-AI",
            f"Risk-{band}",
            r.get("environment", "unknown"),
            mech.capitalize(),
            r.get("floor", ""),
        ]

        issues.append(
            BCFIssue(
                guid=str(uuid.uuid4()).upper(),
                title=f"[BIMGUARD-AI] {band} corrosion risk — {r.get('name', 'Component')}",
                description=(
                    f"Corrosion compliance failure detected by BIMGUARD AI.\n\n"
                    f"Component: {r.get('name', '')}\n"
                    f"Service type: {r.get('description', '')}\n"
                    f"Floor / zone: {r.get('floor', '')}\n"
                    f"Material A: {r.get('material_a', '')}\n"
                    f"Material B: {r.get('material_b', '')}\n"
                    f"Environment: {r.get('environment', '')}\n"
                    f"Galvanic score: {r.get('galvanic_score', 0):.4f} → {r.get('galvanic_band', '')}\n"
                    f"Crevice score:  {r.get('crevice_score', 0):.4f} → {r.get('crevice_band', '')}\n"
                    f"Overall score:  {score:.4f} → {band}\n"
                    f"Dominant mechanism: {mech}\n\n"
                    f"Required action: {r.get('action', '')}\n"
                    f"Mitigation: {r.get('mitigation', '')}\n\n"
                    f"Standards: NASA-STD-6012, EN ISO 15329, ISO 19650\n"
                    f"Ruleset: BIMGUARD-GC-001 + BIMGUARD-CC-001 v1.0.0"
                ),
                priority=priority_map[band],
                status=status_map[band],
                assigned_to=engineer_map[band],
                due_date=due,
                labels=labels,
                component_guid=r.get("guid", str(uuid.uuid4()).upper()),
                component_name=r.get("name", "Component"),
                service_type=r.get("description", ""),
                floor=r.get("floor", ""),
                risk_band=band,
                mechanism=mech,
                risk_score=score,
                mitigation=r.get("mitigation", ""),
                camera_x=float(pos[0]),
                camera_y=float(pos[1]),
                camera_z=float(pos[2]),
                target_x=float(pos[0]),
                target_y=float(pos[1]),
                target_z=float(pos[2]),
            )
        )

    return issues
