"""Tests for the synthetic demo dataset.

WHAT THIS GUARDS

    ``demo_data`` imported the corrosion engines as ``from engines.…`` with a
    ``sys.path`` insert. There has never been a top-level ``engines`` package —
    the engines have always lived at ``app/engines/`` — so every import raised
    ImportError, ``ENGINES_AVAILABLE`` was False, and ``run_demo_compliance()``
    returned hardcoded ``_fallback_results()`` rows. Silently: the except branch
    logged nothing, and the fallback rows look exactly like engine output.

    These tests pin the import so it cannot regress, and assert the fallback is
    distinguishable from a real run.

WHAT THIS DOES NOT CLAIM

    It does not assert the thesis Table 5.1 distribution (9 Critical / 7 High /
    9 Medium). Those figures come from the retired Streamlit-era
    ``issue_tracker.py`` pipeline and cannot be regenerated by this code — see
    ``docs/BIMGuard_3rd_Submission_REVISED.md``. Asserting them here would
    encode a number this module has never produced.

Run: uv run pytest tests/test_demo_data.py -v
"""

from __future__ import annotations

from collections import Counter

import app.engines.demo_data as demo_data


class TestEngineImport:
    """The regression that made the dataset unreproducible."""

    def test_engines_are_importable(self):
        assert demo_data.ENGINES_AVAILABLE is True, (
            "demo_data cannot reach the corrosion engines, so "
            "run_demo_compliance() is returning canned fallback rows"
        )

    def test_engine_symbols_are_bound(self):
        for name in (
            "GCElement",
            "CCElement",
            "MICElement",
            "assess_galvanic_risk",
            "assess_crevice_risk",
            "assess_mic_risk",
        ):
            assert hasattr(demo_data, name), f"{name} did not import"

    def test_imports_use_the_app_package(self):
        """A bare ``from engines.…`` is what broke, so pin the absolute form."""
        source = open(demo_data.__file__, encoding="utf-8").read()
        assert "from app.engines.bimguard_corrosion_engine import" in source
        assert "\nfrom engines." not in source
        assert "    from engines." not in source


class TestDemoDataset:
    """The dataset itself."""

    def test_has_twenty_five_elements(self):
        """The size the thesis describes as the synthetic validation set."""
        assert len(demo_data.DEMO_ELEMENTS) == 25

    def test_every_element_has_an_id(self):
        assert all(e.get("id") for e in demo_data.DEMO_ELEMENTS)

    def test_element_ids_are_unique(self):
        ids = [e["id"] for e in demo_data.DEMO_ELEMENTS]
        assert len(ids) == len(set(ids))


class TestRunDemoCompliance:
    """Output must come from the engines, not the fallback."""

    def test_returns_a_row_per_element(self):
        assert len(demo_data.run_demo_compliance()) == len(demo_data.DEMO_ELEMENTS)

    def test_every_row_carries_all_three_mechanisms(self):
        for row in demo_data.run_demo_compliance():
            assert row.get("gc_band")
            assert row.get("cc_band")
            assert row.get("mc_band")
            assert row.get("combined_band")

    def test_mechanisms_disagree(self):
        """The tell that distinguishes engine output from the fallback.

        Three independent engines scoring twenty-five varied elements do not
        produce identical band distributions. The hardcoded fallback did — that
        is how the silent degrade was spotted.
        """
        rows = demo_data.run_demo_compliance()
        gc = Counter(r["gc_band"] for r in rows)
        cc = Counter(r["cc_band"] for r in rows)
        mc = Counter(r["mc_band"] for r in rows)
        assert not (gc == cc == mc), (
            "all three mechanisms produced identical distributions, which means "
            "these are fallback rows rather than engine output"
        )

    def test_bands_are_the_engine_vocabulary(self):
        """Engines emit Title-case; see data contracts §4.2 on the three casings."""
        allowed = {"Critical", "High", "Medium", "Low"}
        for row in demo_data.run_demo_compliance():
            assert row["combined_band"] in allowed

    def test_summary_totals_match_the_dataset(self):
        rows = demo_data.run_demo_compliance()
        summary = demo_data.get_summary(rows)
        assert summary["total"] == len(demo_data.DEMO_ELEMENTS)
        assert sum(summary["bands"].values()) == summary["total"]

    def test_summary_issue_count_excludes_low(self):
        rows = demo_data.run_demo_compliance()
        summary = demo_data.get_summary(rows)
        assert summary["issues"] == summary["total"] - summary["bands"]["Low"]
