-- Migration: Create public.standards_by_project junction table
-- Date: 2026-08-26
-- Purpose: Link projects to selected standards (both notebook and custom uploaded)
--
-- CORRECTED 2026-08-26: project_id was declared UUID, but public.projects.id is
-- BIGINT (sample ids 4, 8, 11). Postgres rejects a foreign key between uuid and
-- bigint ("Key columns are of incompatible types"), so the original DDL could not
-- run at all. project_id is now BIGINT, and the surrogate key is a bigint identity
-- to match the house style used by projects, documents, rules and report_artifacts.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.standards_by_project (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    standard_id TEXT NOT NULL,
    source      TEXT NOT NULL CHECK (source IN ('notebook', 'uploaded')),
    file_path   TEXT,  -- NULL for notebook standards; set for uploads, e.g. 'standards/project-12/Custom_Spec.pdf'
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_standards_by_project_project_id
    ON public.standards_by_project(project_id);
CREATE INDEX IF NOT EXISTS idx_standards_by_project_standard_id
    ON public.standards_by_project(standard_id);
CREATE INDEX IF NOT EXISTS idx_standards_by_project_source
    ON public.standards_by_project(source);

-- One row per (project, standard, source): makes the wizard's insert idempotent
-- and lets it upsert on conflict rather than duplicating on a re-submit.
CREATE UNIQUE INDEX IF NOT EXISTS idx_standards_by_project_unique
    ON public.standards_by_project(project_id, standard_id, source);

COMMENT ON TABLE  public.standards_by_project IS
    'Junction table linking projects to selected standards (normative references)';
COMMENT ON COLUMN public.standards_by_project.project_id IS
    'Foreign key to public.projects.id (BIGINT)';
COMMENT ON COLUMN public.standards_by_project.standard_id IS
    'Standard identifier: a NOTEBOOK_STANDARDS id (e.g. nasa-12, en-15329) or a generated id for an upload';
COMMENT ON COLUMN public.standards_by_project.source IS
    'Source of standard: notebook (predefined) or uploaded (custom file)';
COMMENT ON COLUMN public.standards_by_project.file_path IS
    'For uploaded standards, the object key in Supabase Storage';

-- RLS: the application connects with the service-role key, which bypasses RLS.
-- Enabling RLS without a policy therefore does not affect the app, but it does
-- deny anon/authenticated clients by default -- the safe posture for a table
-- reachable through PostgREST.
ALTER TABLE public.standards_by_project ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verify:
--   SELECT c.column_name, c.data_type
--     FROM information_schema.columns c
--    WHERE c.table_schema='public' AND c.table_name='standards_by_project'
--    ORDER BY c.ordinal_position;
