-- Extends the RBAC layer (organization_ruleset_grants, project_ruleset_bindings)
-- with the same two-level pattern for projects and documents:
--
-- 1. organization_project_grants: cross-org project sharing. A project's
--    `organization_id` column stays its owning organization (unchanged
--    semantics, still what a fresh project is created into); this table is
--    *additional* access for other organizations, superadmin-controlled --
--    e.g. a client org and the consultancy running the audit both needing
--    the same project.
-- 2. organization_document_grants: which of the global Rule Documents
--    library (public.documents -- no owning organization, same as rulesets
--    before this) an organization may use at all. Superadmin-controlled.
-- 3. project_document_bindings: which of the project's organization's
--    granted documents are actually bound to that project. Owner/admin
--    controlled, always a subset of (2) -- mirrors project_ruleset_bindings.
--    A fresh project has none: "zero bindings unless assigned" again.

create table if not exists public.organization_project_grants (
	id bigint generated by default as identity primary key,
	organization_id bigint not null references public.organizations (id) on delete cascade,
	project_id bigint not null references public.projects (id) on delete cascade,
	created_at timestamptz not null default now(),
	constraint organization_project_grants_key unique (organization_id, project_id)
);

create index if not exists organization_project_grants_project_id_idx on public.organization_project_grants (project_id);

create table if not exists public.organization_document_grants (
	id bigint generated by default as identity primary key,
	organization_id bigint not null references public.organizations (id) on delete cascade,
	document_id bigint not null references public.documents (id) on delete cascade,
	created_at timestamptz not null default now(),
	constraint organization_document_grants_key unique (organization_id, document_id)
);

create index if not exists organization_document_grants_document_id_idx on public.organization_document_grants (document_id);

create table if not exists public.project_document_bindings (
	id bigint generated by default as identity primary key,
	project_id bigint not null references public.projects (id) on delete cascade,
	document_id bigint not null references public.documents (id) on delete cascade,
	created_at timestamptz not null default now(),
	constraint project_document_bindings_key unique (project_id, document_id)
);

create index if not exists project_document_bindings_document_id_idx on public.project_document_bindings (document_id);

alter table public.organization_project_grants enable row level security;
alter table public.organization_document_grants enable row level security;
alter table public.project_document_bindings enable row level security;

revoke all privileges on table public.organization_project_grants from anon, authenticated;
revoke all privileges on table public.organization_document_grants from anon, authenticated;
revoke all privileges on table public.project_document_bindings from anon, authenticated;

grant select, insert, update, delete on table public.organization_project_grants to service_role;
grant select, insert, update, delete on table public.organization_document_grants to service_role;
grant select, insert, update, delete on table public.project_document_bindings to service_role;

revoke usage on sequence public.organization_project_grants_id_seq from anon, authenticated;
revoke usage on sequence public.organization_document_grants_id_seq from anon, authenticated;
revoke usage on sequence public.project_document_bindings_id_seq from anon, authenticated;

grant usage on sequence public.organization_project_grants_id_seq to service_role;
grant usage on sequence public.organization_document_grants_id_seq to service_role;
grant usage on sequence public.project_document_bindings_id_seq to service_role;

-- Backfill: grandfather the default organization into every document that
-- already exists, so today's unrestricted document access doesn't regress.
-- project_document_bindings is deliberately left empty everywhere -- there
-- was never a document-to-project binding concept before this, so there's
-- nothing prior to preserve there, unlike rulesets (which every existing
-- project was actually being evaluated against).
insert into public.organization_document_grants (organization_id, document_id)
select o.id, d.id
from public.organizations o
cross join public.documents d
where o.slug = 'default'
on conflict (organization_id, document_id) do nothing;
