delete from public.app_settings
where key in (
	'BIM_GUARD_STORAGE_BACKEND',
	'BIM_GUARD_LLM_MODEL',
	'BIM_GUARD_RULE_MODEL',
	'OPENAI_MODEL',
	'GEMINI_MODEL',
	'SUPABASE_STORAGE_BUCKET',
	'SUPABASE_STORAGE_PREFIX'
);