-- Migration: Create public.document_pages table
-- Date: 2026-09-04
-- Purpose: Persist page-tagged raw text captured directly from each parsing
-- engine's native per-element page metadata (Docling `prov[].page_no`,
-- Unstructured `metadata.page_number`, pypdf per-page text in
-- LightExtractor). Independent of SectionChunker/LlamaIndexIngestor's
-- clause-node chunking — used only to answer "which page does this rule
-- snippet live on?" for the document viewer / rule-source annotation
-- feature. Empty for pageless formats (CSV/TXT/MD) or engines that don't
-- report page numbers.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.document_pages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id    BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
    page_number    INTEGER NOT NULL,
    text           TEXT NOT NULL DEFAULT '',
    char_count     INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_document_pages_document_id
    ON public.document_pages(document_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_document_pages_unique_page
    ON public.document_pages(document_id, page_number);

COMMENT ON TABLE  public.document_pages IS
    'Page-tagged raw text per document, captured at extraction time for document-viewer page navigation and rule-to-source annotation';
COMMENT ON COLUMN public.document_pages.document_id IS 'Foreign key to public.documents.id';
COMMENT ON COLUMN public.document_pages.page_number IS '1-based source page number';
COMMENT ON COLUMN public.document_pages.text IS 'Raw extracted text for this page';

-- The app uses the service-role key, which bypasses RLS; enabling it denies
-- anon/authenticated clients by default (see client_documents migration).
ALTER TABLE public.document_pages ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verify:
--   SELECT column_name, data_type
--     FROM information_schema.columns
--    WHERE table_schema='public' AND table_name='document_pages'
--    ORDER BY ordinal_position;
