-- Migration: Create public.project_naming_config
-- Date: 2026-08-31
-- Purpose: Hold each project's ISO 19650 information-container naming setup --
--          the base codes that identify the project and its originator, the
--          code subsets that project has chosen to work with, and which naming
--          convention its containers are named by.
--
--          Sourced from docs/experimental/ISO19650_FINDINGS_FROM_NAVISWORKS.md,
--          which documents the five conventions, the 19-token vocabulary and the
--          master code library as implemented in the Navisworks clash platform.
--
-- Column types follow the house style set by project_ifc_files: a BIGINT
-- identity surrogate key, and a BIGINT project_id, because public.projects.id
-- is BIGINT. Declaring project_id as UUID would make the foreign key unrunnable
-- ("Key columns are of incompatible types").
--
-- One row per project, enforced by a UNIQUE constraint rather than left to
-- convention: every read is "the naming setup for this project", and a second
-- row would make which one answers a matter of row order. The service upserts
-- on that constraint, so saving twice edits one row instead of accumulating.
--
-- The code subsets and custom conventions are JSONB rather than child tables.
-- They are read and written whole -- a project's active level codes are only
-- ever fetched together and replaced together -- so rows would buy joins and
-- ordering columns to reconstruct a list the application already treats as one
-- value. JSONB also lets a project carry a custom code the master library has
-- never heard of without a schema migration, which is the documented behaviour:
-- ISO_MASTER_CODES is "never modified -- project codes are separate".
--
-- No CHECK on active_convention. The five presets are joined by any custom
-- convention a project defines, so the set of legal values is per-row data, not
-- a schema constant; a CHECK here would make defining a custom convention a
-- migration. The service falls back to the default when a row names a
-- convention that no longer resolves.
--
-- Idempotent: safe to re-run. Wrapped in a transaction so a failure rolls back
-- cleanly rather than leaving the schema half-migrated.

BEGIN;

CREATE TABLE IF NOT EXISTS public.project_naming_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id          BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,

    -- Base codes (ISO 19650-1 §12, Annex A). project_code and originator_code
    -- are the two the standard requires a project to supply; they default to
    -- empty rather than to a placeholder so an unconfigured project reads as
    -- unconfigured instead of as configured wrongly.
    project_code        TEXT NOT NULL DEFAULT '',
    originator_code     TEXT NOT NULL DEFAULT '',
    type_code           TEXT NOT NULL DEFAULT 'CO',
    suitability         TEXT NOT NULL DEFAULT 'S1',
    revision            TEXT NOT NULL DEFAULT '01',
    separator           TEXT NOT NULL DEFAULT '_',
    date_format         TEXT NOT NULL DEFAULT 'YYMMDD',

    -- Uniclass 2015 classification tokens. Present as real columns because the
    -- source platform offers a Uniclass convention whose {classA}/{classB}
    -- resolve to empty strings, silently yielding names with two empty
    -- segments. Storing them makes that convention produce a usable name.
    class_a             TEXT NOT NULL DEFAULT '',
    class_b             TEXT NOT NULL DEFAULT '',

    active_convention   TEXT NOT NULL DEFAULT 'iso19650_date',

    -- Subsets of the master library this project works with, each a JSON array
    -- of {code, label} objects. Empty array means "the project has not narrowed
    -- the library", which the service reads as the full master set.
    level_codes         JSONB NOT NULL DEFAULT '[]'::jsonb,
    type_codes          JSONB NOT NULL DEFAULT '[]'::jsonb,
    discipline_codes    JSONB NOT NULL DEFAULT '[]'::jsonb,
    volume_codes        JSONB NOT NULL DEFAULT '[]'::jsonb,

    -- Conventions defined by this project, each {id, name, separator, format,
    -- description}. Presets are served from code and are not stored here.
    custom_conventions  JSONB NOT NULL DEFAULT '[]'::jsonb,

    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- One naming setup per project. Also the conflict target the service upserts
-- on, so it must exist before any write path runs.
CREATE UNIQUE INDEX IF NOT EXISTS uq_project_naming_config_project_id
    ON public.project_naming_config(project_id);

COMMENT ON TABLE  public.project_naming_config IS
    'ISO 19650 information-container naming setup; exactly one row per project';
COMMENT ON COLUMN public.project_naming_config.project_id IS
    'Foreign key to public.projects.id (BIGINT); the row dies with the project';
COMMENT ON COLUMN public.project_naming_config.project_code IS
    'Unique project identifier, e.g. A1234 (ISO 19650-1 Annex A)';
COMMENT ON COLUMN public.project_naming_config.originator_code IS
    'Author / issuing organisation, e.g. BIM01';
COMMENT ON COLUMN public.project_naming_config.type_code IS
    'Information type: CO correspondence, RP report, MO model';
COMMENT ON COLUMN public.project_naming_config.suitability IS
    'CDE status (ISO 19650-2 Table 1): S0, S1, S2, S3 or A';
COMMENT ON COLUMN public.project_naming_config.revision IS
    'Revision, e.g. 01; P01 preliminary, C01 contract';
COMMENT ON COLUMN public.project_naming_config.separator IS
    'Field separator used when rendering a name: _, - or .';
COMMENT ON COLUMN public.project_naming_config.date_format IS
    'YYMMDD, DDMMYY, YYYYMMDD, DD-MM-YY or ISO';
COMMENT ON COLUMN public.project_naming_config.class_a IS
    'Uniclass 2015 primary classification token, used by the uniclass convention';
COMMENT ON COLUMN public.project_naming_config.class_b IS
    'Uniclass 2015 secondary classification token';
COMMENT ON COLUMN public.project_naming_config.active_convention IS
    'id of the convention names are rendered by; a preset or a custom_conventions entry';
COMMENT ON COLUMN public.project_naming_config.level_codes IS
    'JSON array of {code,label} this project narrows the level library to; [] means all';
COMMENT ON COLUMN public.project_naming_config.custom_conventions IS
    'JSON array of {id,name,separator,format,description} defined by this project';

COMMIT;
