-- Migration: Create public.rule_extraction_drafts table
-- Date: 2026-09-02
-- Purpose: Persist LLM-extracted rule candidates with an approve/reject/edit
-- review workflow before they are promoted into the canonical public.rules
-- table. Closes a gap where extracted rules previously lived only in the
-- frontend's in-memory state (RuleExtractionView.svelte) and were lost on
-- refresh, with no reviewer identity, timestamp, or audit trail.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.rule_extraction_drafts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_document_id  BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
    source_node_id      TEXT,
    clause              JSONB,
    proposed_rule        JSONB NOT NULL,
    confidence          DOUBLE PRECISION NOT NULL DEFAULT 0.8 CHECK (confidence >= 0 AND confidence <= 1),
    extraction_method    TEXT NOT NULL DEFAULT 'litellm_legacy' CHECK (extraction_method IN (
        'llamaindex_pydantic', 'litellm_legacy'
    )),
    status               TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN (
        'pending_review', 'accepted', 'rejected', 'edited'
    )),
    reviewer_email       TEXT,
    reviewed_at          TIMESTAMP WITH TIME ZONE,
    review_notes         TEXT,
    promoted_rule_id      BIGINT REFERENCES public.rules(id) ON DELETE SET NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rule_extraction_drafts_document_id
    ON public.rule_extraction_drafts(source_document_id);
CREATE INDEX IF NOT EXISTS idx_rule_extraction_drafts_status
    ON public.rule_extraction_drafts(status);

COMMENT ON TABLE  public.rule_extraction_drafts IS
    'LLM-extracted rule candidates awaiting review/promotion into public.rules; fixes the prior lack of a persisted extraction-draft state';
COMMENT ON COLUMN public.rule_extraction_drafts.source_document_id IS 'Foreign key to public.documents.id';
COMMENT ON COLUMN public.rule_extraction_drafts.source_node_id IS 'Links back to a DocumentNodeContract.node_id, when ingested via LlamaIndexIngestor';
COMMENT ON COLUMN public.rule_extraction_drafts.clause IS 'JSON ClauseMetadata for the source clause, when known';
COMMENT ON COLUMN public.rule_extraction_drafts.proposed_rule IS 'JSON RuleCreateRequest payload proposed by the extractor';
COMMENT ON COLUMN public.rule_extraction_drafts.promoted_rule_id IS 'Set once the draft has been promoted into public.rules';

-- The app uses the service-role key, which bypasses RLS; enabling it denies
-- anon/authenticated clients by default (see client_documents migration).
ALTER TABLE public.rule_extraction_drafts ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Verify:
--   SELECT column_name, data_type
--     FROM information_schema.columns
--    WHERE table_schema='public' AND table_name='rule_extraction_drafts'
--    ORDER BY ordinal_position;
