-- Generated by scripts/patch_nzs4219_513_scope.py --retire-proxy --print-sql.
-- Do not hand-edit: change the constants in that script and regenerate.
--
-- Retire proxy in NZS-4219-5.13 scope.
-- Drops the nominal_diameter_mm proxy now that mass_kg is extractable.
-- The keys are ANDed, so leaving the band in place would drop a heavy
-- small-bore run out of scope -- a false negative the clause does not
-- intend. The IfcPipeSegment narrowing from the v1 patch is kept.
-- `applies_when` and `parameters` are text columns holding JSON (see
-- supabase/migrations/20260721135500_init_core_public_tables.sql), hence the
-- ::jsonb round trip on the merge.
update public.rules
   set target_ifc_class = 'IfcPipeSegment',
       description      = 'Seismic clearance for independently supported pipework in ceiling voids.',
       applies_when     = '{"target_ifc_class": "IfcPipeSegment", "location": "ceiling_void", "mass_kg": {"min": 10.0}}',
       parameters       = (coalesce(nullif(parameters, ''), '{}')::jsonb || jsonb_build_object('scope_patch', '{"patcher": "patch_nzs4219_513_scope/2", "supersedes": "patch_nzs4219_513_scope/1", "removed_key": "nominal_diameter_mm", "removed_min_mm": 50.0, "reason": "mass_kg is resolvable by module2_ifc_read.ifc_seismic and mapped in module4_comparator._SCOPE_NUMERIC_PROPERTIES, which is the condition scope_patch.retire_proxy_when named. Keeping the band would AND with the mass gate and drop a heavy small-bore run out of scope.", "target_ifc_class_retained": "IfcPipeSegment", "previous_applies_when": {"target_ifc_class": "IfcPipeSegment", "nominal_diameter_mm": {"min": 50.0}, "location": "ceiling_void", "mass_kg": {"min": 10.0}, "note": "mass_kg >= 10 is the clause''s own threshold and is not resolvable by the extractor today; nominal bore 50 mm and above is the enforceable proxy. Drop nominal_diameter_mm once mass_kg is extractable -- the keys are ANDed, so keeping both would then exclude heavy small-bore runs."}}'::jsonb))::text,
       updated_at       = to_char(now() at time zone 'utc',
                                  'YYYY-MM-DD"T"HH24:MI:SS+00:00')
 where reference = 'NZS-4219-5.13';

