create table public.report_artifacts (
	id bigint generated by default as identity primary key,
	project_id bigint not null references public.projects(id) on delete cascade,
	artifact_type text not null,
	filename text not null,
	storage_ref text not null,
	content_type text not null default 'application/octet-stream',
	byte_size bigint not null check (byte_size >= 0),
	sha256 text not null check (length(sha256) = 64),
	issue_count integer not null default 0 check (issue_count >= 0),
	created_at timestamptz not null default now(),
	constraint report_artifacts_storage_ref_key unique (storage_ref)
);

create index report_artifacts_project_type_created_idx
on public.report_artifacts (project_id, artifact_type, created_at desc);

alter table public.report_artifacts enable row level security;

revoke all privileges on table public.report_artifacts from anon, authenticated;
grant select, insert, delete on table public.report_artifacts to service_role;

revoke usage on sequence public.report_artifacts_id_seq from anon, authenticated;
grant usage on sequence public.report_artifacts_id_seq to service_role;
