begin;

-- Normalize whitespace first.
update public.rules
set ruleset_id = regexp_replace(trim(coalesce(ruleset_id, '')), '\\s+', ' ', 'g')
where coalesce(ruleset_id, '') <> '';

-- Canonicalize case-variant duplicates in rules by keeping earliest spelling.
with canonical as (
    select distinct on (lower(ruleset_id))
        lower(ruleset_id) as norm_key,
        ruleset_id as canonical_ruleset_id
    from public.rules
    where ruleset_id <> ''
    order by lower(ruleset_id), id
)
update public.rules r
set ruleset_id = c.canonical_ruleset_id
from canonical c
where r.ruleset_id <> ''
and lower(r.ruleset_id) = c.norm_key
and r.ruleset_id <> c.canonical_ruleset_id;

create table if not exists public.rule_folders (
    id bigint generated by default as identity primary key,
    ruleset_id text not null default '',
    display_name text not null default '',
    description text not null default '',
    mechanism_scope text not null default '',
    created_at text not null default '',
    updated_at text not null default ''
);

alter table public.rule_folders
    add column if not exists ruleset_id text not null default '',
    add column if not exists display_name text not null default '',
    add column if not exists description text not null default '',
    add column if not exists mechanism_scope text not null default '',
    add column if not exists created_at text not null default '',
    add column if not exists updated_at text not null default '';

update public.rule_folders
set
    ruleset_id = regexp_replace(trim(coalesce(ruleset_id, '')), '\\s+', ' ', 'g'),
    display_name = trim(coalesce(display_name, '')),
    description = trim(coalesce(description, '')),
    mechanism_scope = upper(trim(coalesce(mechanism_scope, '')));

-- Canonicalize existing folder rows by case-insensitive key, keeping oldest row.
with ranked as (
    select
        id,
        lower(ruleset_id) as norm_key,
        row_number() over (partition by lower(ruleset_id) order by id) as rn
    from public.rule_folders
    where ruleset_id <> ''
)
delete from public.rule_folders rf
using ranked r
where rf.id = r.id and r.rn > 1;

-- Normalize/validate mechanism scope.
update public.rule_folders
set mechanism_scope = ''
where mechanism_scope not in ('', 'OBC', 'GC-001', 'CC-001', 'MC-001', 'IFC');

-- Fill missing display_name with ruleset_id.
update public.rule_folders
set display_name = ruleset_id
where display_name = '' and ruleset_id <> '';

-- Backfill folders from canonicalized rules.
insert into public.rule_folders (
    ruleset_id,
    display_name,
    description,
    mechanism_scope,
    created_at,
    updated_at
)
select
    c.canonical_ruleset_id,
    c.canonical_ruleset_id,
    '',
    c.mechanism_scope,
    c.created_at,
    c.updated_at
from (
    select distinct on (lower(r.ruleset_id))
        lower(r.ruleset_id) as norm_key,
        r.ruleset_id as canonical_ruleset_id,
        case
            when upper(trim(coalesce(r.mechanism, ''))) in ('OBC', 'GC-001', 'CC-001', 'MC-001', 'IFC')
                then upper(trim(coalesce(r.mechanism, '')))
            else ''
        end as mechanism_scope,
        coalesce(r.created_at, '') as created_at,
        coalesce(r.updated_at, '') as updated_at
    from public.rules r
    where coalesce(r.ruleset_id, '') <> ''
    order by lower(r.ruleset_id), r.id
) c
where not exists (
    select 1
    from public.rule_folders f
    where lower(f.ruleset_id) = c.norm_key
);

create unique index if not exists rule_folders_ruleset_id_key
on public.rule_folders ((lower(ruleset_id)))
where ruleset_id <> '';

alter table public.rule_folders enable row level security;

revoke all privileges on table public.rule_folders from anon, authenticated;
grant select, insert, update, delete on table public.rule_folders to service_role;

do $$
begin
    if to_regclass('public.rule_folders_id_seq') is not null then
        revoke usage on sequence public.rule_folders_id_seq from anon, authenticated;
        grant usage on sequence public.rule_folders_id_seq to service_role;
    end if;
end
$$;

commit;
