-- Pending org invites: lets an organization list a member by email before
-- that person has ever signed in. MembershipService consumes matching rows
-- (by email, case-insensitively) the first time that address signs in with
-- Google, turning the invite into a real membership. No email is sent by
-- this table on its own -- it is purely a "who belongs where" mapping.

create table if not exists public.organization_invites (
	id bigint generated by default as identity primary key,
	organization_id bigint not null references public.organizations (id) on delete cascade,
	email text not null,
	role text not null default 'member' check (role in ('owner', 'admin', 'member')),
	created_at timestamptz not null default now(),
	accepted_at timestamptz,
	constraint organization_invites_org_email_key unique (organization_id, email)
);

create index if not exists organization_invites_email_idx on public.organization_invites (lower(email));
create index if not exists organization_invites_organization_id_idx on public.organization_invites (organization_id);

alter table public.organization_invites enable row level security;

revoke all privileges on table public.organization_invites from anon, authenticated;
grant select, insert, update, delete on table public.organization_invites to service_role;

revoke usage on sequence public.organization_invites_id_seq from anon, authenticated;
grant usage on sequence public.organization_invites_id_seq to service_role;

-- A global bypass flag: a superadmin's requests skip organization-membership
-- checks entirely (see app.api.projects.get_authorized_project), rather than
-- being scoped to any one organization.
alter table public.profiles add column if not exists is_superadmin boolean not null default false;

-- Seed the two real organizations.
insert into public.organizations (name, slug)
values
	('Archinova', 'archinova'),
	('Aspiring Design 3D Consultancy Ltd', 'aspiring-design-3d')
on conflict (slug) do nothing;

-- Seed pending invites for their members (none have signed in yet).
insert into public.organization_invites (organization_id, email, role)
select o.id, v.email, 'member'
from (
	values
		('archinova', 'malak.yaseen@gmail.com'),
		('archinova', 'marc.m.azzam@gmail.com'),
		('archinova', 'clementeleticia.lc@gmail.com'),
		('aspiring-design-3d', 'shane.haines@ad3d.co.nz'),
		('aspiring-design-3d', 'markshanehaines@gmail.com'),
		('aspiring-design-3d', 'clementeleticia.lc@gmail.com')
) as v(slug, email)
join public.organizations o on o.slug = v.slug
on conflict (organization_id, email) do nothing;

-- Mark the existing signed-in account as the platform superadmin.
update public.profiles
set is_superadmin = true
where id = (select id from auth.users where email = 'eng.superosama@gmail.com');
