create table public.model_enhancement_lineage (
	id bigint generated by default as identity primary key,
	project_id bigint not null references public.projects(id),
	source_reference text not null,
	output_reference text not null,
	version bigint not null check (version > 0),
	summary jsonb not null default '{}'::jsonb,
	created_at timestamptz not null default now(),
	constraint model_enhancement_lineage_project_version_key unique (project_id, version),
	constraint model_enhancement_lineage_distinct_artifacts_check check (source_reference <> output_reference)
);

alter table public.model_enhancement_lineage enable row level security;

revoke all privileges on table public.model_enhancement_lineage from anon, authenticated;
grant select, insert on table public.model_enhancement_lineage to service_role;

revoke usage on sequence public.model_enhancement_lineage_id_seq from anon, authenticated;
grant usage on sequence public.model_enhancement_lineage_id_seq to service_role;