-- Migration: create_rule_check_categories
-- Date: 2026-09-29
-- Purpose: Analysis results are grouped per element type (Windows, Doors, ...)
-- and, within each, by the topic a rule checks -- "Fire and Smoke Protection",
-- "Emergency Escape", and so on. That topic list is data, not code: it lives
-- here so it can be renamed, reordered or extended without a deploy, and each
-- rule points at one entry via public.rules.check_category.
--
-- check_category is distinct from the existing rules.rule_category column,
-- which classifies the check MECHANISM (property_check, threshold_band, ...).
--
-- The FK references the category NAME (unique) so a rename cascades to every
-- rule, and deleting a category leaves its rules uncategorized rather than
-- deleting them.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.rule_check_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    -- What the category tests; shown under its heading and given to the
    -- extraction LLM so it can tell neighbouring categories apart.
    description text NOT NULL DEFAULT '',
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.rule_check_categories IS
    'Ordered list of check categories used to group rule results under each element type in the analysis view.';

-- The app uses the service-role key, which bypasses RLS; enabling it denies
-- anon/authenticated clients by default.
ALTER TABLE public.rule_check_categories ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.rule_check_categories FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.rule_check_categories TO service_role;

REVOKE USAGE ON SEQUENCE public.rule_check_categories_id_seq FROM anon, authenticated;
GRANT USAGE ON SEQUENCE public.rule_check_categories_id_seq TO service_role;

INSERT INTO public.rule_check_categories (name, description, sort_order) VALUES
    ('Core Dimensions and Relationships', 'Fundamental size, opening, host, storey, building, and space relationships used by many downstream tests.', 1),
    ('Fire and Smoke Protection', 'Fire-rating, smoke-control, and exterior-context evidence used for protected-opening applicability and checks.', 2),
    ('Energy Performance', 'Thermal, solar, glazing-fraction, and air-leakage values used in envelope performance checks.', 3),
    ('Emergency Escape', 'Clear opening dimensions and sill position used for emergency escape and rescue-opening checks.', 4),
    ('Acoustic and Materials', 'Acoustic performance and the main frame/glazing construction information.', 5),
    ('Safety, Security and Glazing', 'Safety-glazing and security evidence used to verify hazardous-location and product requirements.', 6),
    ('Light, Ventilation and Space Ratios', 'Glazing, optical, openable-area, and floor-area ratios used for daylight and natural-ventilation testing.', 7),
    ('Type, Naming and Identification', 'Window identity, type assignment, naming, marks, family, and standardized type descriptors.', 8),
    ('Classification and Manufacturer Data', 'Project classification references and manufacturer/product identification.', 9),
    ('Geometry and Placement Validation', 'Geometry estimates, placement checks, intersections, containment, and geometric health tests.', 10),
    ('Consistency and Cross-Validation', 'Repeatable comparisons between authored values, geometry, occurrences, and assigned types.', 11),
    ('Units, Global IDs and Provenance', 'Project units, persistent IFC identifiers, and reporting provenance needed for traceable results.', 12)
ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.rules
    ADD COLUMN IF NOT EXISTS check_category text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'rules_check_category_fkey'
    ) THEN
        ALTER TABLE public.rules
            ADD CONSTRAINT rules_check_category_fkey
            FOREIGN KEY (check_category)
            REFERENCES public.rule_check_categories (name)
            ON UPDATE CASCADE
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_rules_check_category
    ON public.rules (check_category);

COMMENT ON COLUMN public.rules.check_category IS
    'Name of the rule_check_categories entry this rule is grouped under in analysis results; NULL = uncategorized.';

-- Property -> category map. Rules are categorised from their target class and
-- property_name when no category is set explicitly (see
-- RuleCheckCategoryService.category_for_property). Seeded from the
-- "BIMGuard Window Properties - Functional Categories and Accuracy Table":
-- its 88 window properties, plus the IFC names some rules use for the same
-- values (OverallWidth/OverallHeight, SolarHeatGainTransmittance for SHGC,
-- GlassThickness1-3, IsTempered/IsLaminated).
CREATE TABLE IF NOT EXISTS public.rule_check_category_properties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_ifc_class text NOT NULL,
    property_name text NOT NULL,
    check_category text NOT NULL
        REFERENCES public.rule_check_categories (name) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_rule_check_category_properties_class_prop
    ON public.rule_check_category_properties (lower(target_ifc_class), lower(property_name));

ALTER TABLE public.rule_check_category_properties ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.rule_check_category_properties FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.rule_check_category_properties TO service_role;

REVOKE USAGE ON SEQUENCE public.rule_check_category_properties_id_seq FROM anon, authenticated;
GRANT USAGE ON SEQUENCE public.rule_check_category_properties_id_seq TO service_role;

INSERT INTO public.rule_check_category_properties (target_ifc_class, property_name, check_category) VALUES
    ('IfcWindow', 'Width', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'Height', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'Area', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'HeadHeight', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'AspectRatio', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'OpeningElement', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'HostElement', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'OpeningCount', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'HostCount', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'Storey', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'Building', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'HostType', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'SpaceConnection', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'OverallWidth', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'OverallHeight', 'Core Dimensions and Relationships'),
    ('IfcWindow', 'FireRating', 'Fire and Smoke Protection'),
    ('IfcWindow', 'SmokeStop', 'Fire and Smoke Protection'),
    ('IfcWindow', 'IsExternalConsistency', 'Fire and Smoke Protection'),
    ('IfcWindow', 'ThermalTransmittance', 'Energy Performance'),
    ('IfcWindow', 'Infiltration', 'Energy Performance'),
    ('IfcWindow', 'SHGC', 'Energy Performance'),
    ('IfcWindow', 'SolarHeatGainTransmittance', 'Energy Performance'),
    ('IfcWindow', 'GlazingAreaFraction', 'Energy Performance'),
    ('IfcWindow', 'ClearOpeningWidth', 'Emergency Escape'),
    ('IfcWindow', 'ClearOpeningHeight', 'Emergency Escape'),
    ('IfcWindow', 'ClearOpeningArea', 'Emergency Escape'),
    ('IfcWindow', 'SillHeight', 'Emergency Escape'),
    ('IfcWindow', 'AcousticRating', 'Acoustic and Materials'),
    ('IfcWindow', 'FrameMaterial', 'Acoustic and Materials'),
    ('IfcWindow', 'GlassMaterial', 'Acoustic and Materials'),
    ('IfcWindow', 'GlassLayers', 'Acoustic and Materials'),
    ('IfcWindow', 'GlassThickness', 'Acoustic and Materials'),
    ('IfcWindow', 'GlassThickness1', 'Acoustic and Materials'),
    ('IfcWindow', 'GlassThickness2', 'Acoustic and Materials'),
    ('IfcWindow', 'GlassThickness3', 'Acoustic and Materials'),
    ('IfcWindow', 'IsSafetyGlass', 'Safety, Security and Glazing'),
    ('IfcWindow', 'IsTemperedOrLaminated', 'Safety, Security and Glazing'),
    ('IfcWindow', 'IsTempered', 'Safety, Security and Glazing'),
    ('IfcWindow', 'IsLaminated', 'Safety, Security and Glazing'),
    ('IfcWindow', 'SecurityRating', 'Safety, Security and Glazing'),
    ('IfcWindow', 'GlazingArea', 'Light, Ventilation and Space Ratios'),
    ('IfcWindow', 'VisibleLightTransmittance', 'Light, Ventilation and Space Ratios'),
    ('IfcWindow', 'OpenableAreaFloorRatio', 'Light, Ventilation and Space Ratios'),
    ('IfcWindow', 'GlazingAreaFloorRatio', 'Light, Ventilation and Space Ratios'),
    ('IfcWindow', 'WindowAreaFloorRatio', 'Light, Ventilation and Space Ratios'),
    ('IfcWindow', 'Name', 'Type, Naming and Identification'),
    ('IfcWindow', 'Tag', 'Type, Naming and Identification'),
    ('IfcWindow', 'Mark', 'Type, Naming and Identification'),
    ('IfcWindow', 'Family', 'Type, Naming and Identification'),
    ('IfcWindow', 'PredefinedType', 'Type, Naming and Identification'),
    ('IfcWindow', 'ObjectType', 'Type, Naming and Identification'),
    ('IfcWindow', 'PartitioningType', 'Type, Naming and Identification'),
    ('IfcWindow', 'WindowType', 'Type, Naming and Identification'),
    ('IfcWindow', 'TypeName', 'Type, Naming and Identification'),
    ('IfcWindow', 'TypeMark', 'Type, Naming and Identification'),
    ('IfcWindow', 'TypeAssignmentCount', 'Type, Naming and Identification'),
    ('IfcWindow', 'Reference', 'Classification and Manufacturer Data'),
    ('IfcWindow', 'ClassificationCode', 'Classification and Manufacturer Data'),
    ('IfcWindow', 'ClassificationSystem', 'Classification and Manufacturer Data'),
    ('IfcWindow', 'Manufacturer', 'Classification and Manufacturer Data'),
    ('IfcWindow', 'ModelReference', 'Classification and Manufacturer Data'),
    ('IfcWindow', 'GeometricWidth', 'Geometry and Placement Validation'),
    ('IfcWindow', 'GeometricHeight', 'Geometry and Placement Validation'),
    ('IfcWindow', 'GeometricDepth', 'Geometry and Placement Validation'),
    ('IfcWindow', 'OpeningIntersection', 'Geometry and Placement Validation'),
    ('IfcWindow', 'HostIntersection', 'Geometry and Placement Validation'),
    ('IfcWindow', 'OrientationAzimuth', 'Geometry and Placement Validation'),
    ('IfcWindow', 'LocalAxesOrthogonal', 'Geometry and Placement Validation'),
    ('IfcWindow', 'InsideOpening', 'Geometry and Placement Validation'),
    ('IfcWindow', 'NonDegenerateGeometry', 'Geometry and Placement Validation'),
    ('IfcWindow', 'NumericValuesValid', 'Geometry and Placement Validation'),
    ('IfcWindow', 'InsideWindowExtents', 'Geometry and Placement Validation'),
    ('IfcWindow', 'Placement', 'Geometry and Placement Validation'),
    ('IfcWindow', 'BodyRepresentation', 'Geometry and Placement Validation'),
    ('IfcWindow', 'WidthDifference', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'HeightDifference', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'InstanceTypeWidthDifference', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'InstanceTypeHeightDifference', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'InstanceTypeFireRatingMatch', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'InstanceTypeExternalMatch', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'InstanceTypeAcousticMatch', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'InstanceTypeUValueDifference', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'KeyPropertiesConsistent', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'GlassOpticalValuesValid', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'PerformanceValuesNonNegative', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'TypeNameConsistency', 'Consistency and Cross-Validation'),
    ('IfcWindow', 'ProjectUnits', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'WidthUnit', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'HeightUnit', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'AreaUnit', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'GlobalId', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'TypeGlobalId', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'OpeningGlobalId', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'HostGlobalId', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'StoreyGlobalId', 'Units, Global IDs and Provenance'),
    ('IfcWindow', 'RawPropertyProvenance', 'Units, Global IDs and Provenance')
ON CONFLICT DO NOTHING;

-- Categorise existing rules the map covers; explicit categories are kept.
UPDATE public.rules AS r
   SET check_category = m.check_category
  FROM public.rule_check_category_properties AS m
 WHERE r.check_category IS NULL
   AND lower(r.target_ifc_class) = lower(m.target_ifc_class)
   AND lower(r.property_name) = lower(m.property_name);

COMMIT;

-- Verify:
--   SELECT name, sort_order FROM public.rule_check_categories ORDER BY sort_order;
--   SELECT check_category, count(*) FROM public.rule_check_category_properties GROUP BY 1;
--   SELECT reference, property_name, check_category FROM public.rules WHERE target_ifc_class = 'IfcWindow';
--   SELECT column_name FROM information_schema.columns
--    WHERE table_schema='public' AND table_name='rules' AND column_name='check_category';
