-- Migration: Create public.uploaded_files
-- Date: 2026-08-27
-- Purpose: Record where each uploaded artefact went and what it hashed to, so
--          an identical re-upload can reuse the stored object and its parse
--          instead of repeating both.
--
-- Column types follow the house style set by projects / standards_by_project:
-- a BIGINT identity surrogate key, and a BIGINT project_id, because
-- public.projects.id is BIGINT. Declaring project_id as UUID would make the
-- foreign key unrunnable ("Key columns are of incompatible types") — the exact
-- defect corrected in migration 002.
--
-- Hashing note: this table stores SHA-256, matching model lineage and the
-- Phase 6B parser. public.projects.ifc_md5_hash predates that convention and is
-- deliberately left alone; reconciling it is a separate change of its own.
--
-- Idempotent: safe to re-run. Wrapped in a transaction so a failure rolls back
-- cleanly rather than leaving the schema half-migrated.

BEGIN;

CREATE TABLE IF NOT EXISTS public.uploaded_files (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id        BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    kind              TEXT NOT NULL DEFAULT 'ifc' CHECK (kind IN ('ifc', 'document', 'standard')),
    filename          TEXT NOT NULL,
    storage_ref       TEXT NOT NULL,
    file_hash_sha256  TEXT NOT NULL,
    size_bytes        BIGINT NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Lookups are by content hash (re-upload detection) and by project (listing a
-- project's artefacts). Neither is unique: the same bytes may legitimately be
-- uploaded against more than one project, and a project may hold many files.
CREATE INDEX IF NOT EXISTS idx_uploaded_files_hash
    ON public.uploaded_files(file_hash_sha256);
CREATE INDEX IF NOT EXISTS idx_uploaded_files_project_id
    ON public.uploaded_files(project_id);
CREATE INDEX IF NOT EXISTS idx_uploaded_files_kind
    ON public.uploaded_files(kind);

-- project_id is nullable on purpose: a file may be uploaded before the project
-- row exists (the wizard collects the model at step 4, but only inserts the
-- project on submit at step 5).
COMMENT ON TABLE  public.uploaded_files IS
    'Storage references and SHA-256 digests for uploaded IFC models, documents and standards';
COMMENT ON COLUMN public.uploaded_files.project_id IS
    'Foreign key to public.projects.id (BIGINT); NULL until the project is created';
COMMENT ON COLUMN public.uploaded_files.storage_ref IS
    'ObjectStorage reference, e.g. sb://bucket/uploads/ifc/<uuid>_model.ifc';
COMMENT ON COLUMN public.uploaded_files.file_hash_sha256 IS
    'Hex SHA-256 of the stored bytes; the cache key shared with the Phase 6B parser';

COMMIT;
