-- Generated by scripts/patch_nzs4219_513_scope.py --print-sql.
-- Do not hand-edit: change the constants in that script and regenerate.
--
-- Patch NZS-4219-5.13 scope.
-- Narrows IfcDistributionElement -> IfcPipeSegment and adds the
-- enforceable nominal-bore band that proxies for mass_kg.
-- `applies_when` and `parameters` are text columns holding JSON (see
-- supabase/migrations/20260721135500_init_core_public_tables.sql), hence the
-- ::jsonb round trip on the merge.
update public.rules
   set target_ifc_class = 'IfcPipeSegment',
       description      = 'Seismic clearance for independently supported pipework in ceiling voids, nominal bore 50 mm and above.',
       applies_when     = '{"target_ifc_class": "IfcPipeSegment", "nominal_diameter_mm": {"min": 50.0}, "location": "ceiling_void", "mass_kg": {"min": 10.0}, "note": "mass_kg >= 10 is the clause''s own threshold and is not resolvable by the extractor today; nominal bore 50 mm and above is the enforceable proxy. Drop nominal_diameter_mm once mass_kg is extractable -- the keys are ANDed, so keeping both would then exclude heavy small-bore runs."}',
       parameters       = (coalesce(nullif(parameters, ''), '{}')::jsonb || jsonb_build_object('scope_patch', '{"patcher": "patch_nzs4219_513_scope/1", "narrowed_target_from": "IfcDistributionElement", "narrowed_target_to": "IfcPipeSegment", "proxy_key": "nominal_diameter_mm", "proxy_min_mm": 50.0, "proxy_for": "mass_kg", "proxy_for_min": 10.0, "proxy_is_not_clause_text": true, "previous_applies_when": {"target_ifc_class": "IfcDistributionElement", "location": "ceiling_void", "mass_kg": {"min": 10.0}}, "retire_proxy_when": "mass_kg is added to comparator._SCOPE_NUMERIC_PROPERTIES"}'::jsonb))::text,
       updated_at       = to_char(now() at time zone 'utc',
                                  'YYYY-MM-DD"T"HH24:MI:SS+00:00')
 where reference = 'NZS-4219-5.13';

