begin;

create table if not exists public.static_data_assets (
    id bigint generated by default as identity primary key,
    asset_key text not null,
    source_path text not null default '',
    format text not null default 'json',
    content_json text not null default '{}',
    content_text text not null default '',
    content_sha256 text not null default '',
    migrated_at text not null default '',
    active integer not null default 1
);

create unique index if not exists static_data_assets_asset_key_key
on public.static_data_assets (asset_key);

create table if not exists public.app_settings (
    key text primary key,
    value text not null default '',
    value_type text not null default 'string',
    scope text not null default 'runtime',
    is_secret integer not null default 0,
    description text not null default '',
    updated_at text not null default ''
);

create table if not exists public.issue_history (
    global_id text primary key,
    payload_json text not null default '{}',
    updated_at text not null default ''
);

alter table public.static_data_assets enable row level security;
alter table public.app_settings enable row level security;
alter table public.issue_history enable row level security;

revoke all privileges on table public.static_data_assets from anon, authenticated;
revoke all privileges on table public.app_settings from anon, authenticated;
revoke all privileges on table public.issue_history from anon, authenticated;

grant select, insert, update, delete on table public.static_data_assets to service_role;
grant select, insert, update, delete on table public.app_settings to service_role;
grant select, insert, update, delete on table public.issue_history to service_role;

do $$
begin
    if to_regclass('public.static_data_assets_id_seq') is not null then
        revoke usage on sequence public.static_data_assets_id_seq from anon, authenticated;
        grant usage on sequence public.static_data_assets_id_seq to service_role;
    end if;
end
$$;

insert into public.app_settings (key, value, value_type, scope, is_secret, description, updated_at)
values
    ('BIM_GUARD_STORAGE_BACKEND', 'supabase', 'string', 'runtime', 0, 'Object storage backend selector: local | supabase.', ''),
    ('BIM_GUARD_RULE_MODEL', 'gpt-4o-mini', 'string', 'runtime', 0, 'Default LiteLLM model used for rule extraction.', ''),
    ('OPENAI_MODEL', 'gpt-4o-mini', 'string', 'legacy', 0, 'Legacy Module 3 model fallback.', ''),
    ('GEMINI_MODEL', 'gemini-1.5-flash', 'string', 'legacy', 0, 'Legacy Gemini model fallback.', ''),
    ('SUPABASE_STORAGE_BUCKET', 'bim-guard-artifacts', 'string', 'runtime', 0, 'Supabase bucket used for artifact uploads.', ''),
    ('SUPABASE_STORAGE_PREFIX', '', 'string', 'runtime', 0, 'Optional key prefix for artifacts in Supabase Storage.', '')
on conflict (key) do nothing;

commit;
