-- Migration: create_rule_check_categories
-- Date: 2026-09-29
-- Purpose: Analysis results are grouped per element type (Windows, Doors, ...)
-- and, within each, by the topic a rule checks -- "Fire and Smoke Protection",
-- "Emergency Escape", and so on. That topic list is data, not code: it lives
-- here so it can be renamed, reordered or extended without a deploy, and each
-- rule points at one entry via public.rules.check_category.
--
-- check_category is distinct from the existing rules.rule_category column,
-- which classifies the check MECHANISM (property_check, threshold_band, ...).
--
-- The FK references the category NAME (unique) so a rename cascades to every
-- rule, and deleting a category leaves its rules uncategorized rather than
-- deleting them.
--
-- Idempotent: safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS public.rule_check_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.rule_check_categories IS
    'Ordered list of check categories used to group rule results under each element type in the analysis view.';

-- The app uses the service-role key, which bypasses RLS; enabling it denies
-- anon/authenticated clients by default.
ALTER TABLE public.rule_check_categories ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.rule_check_categories FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.rule_check_categories TO service_role;

REVOKE USAGE ON SEQUENCE public.rule_check_categories_id_seq FROM anon, authenticated;
GRANT USAGE ON SEQUENCE public.rule_check_categories_id_seq TO service_role;

INSERT INTO public.rule_check_categories (name, sort_order) VALUES
    ('Geometry and Placement Validation', 1),
    ('Core Dimensions and Relationships', 2),
    ('Fire and Smoke Protection', 3),
    ('Energy Performance', 4),
    ('Emergency Escape', 5),
    ('Safety, Security and Glazing', 6),
    ('Light, Ventilation and Space Ratios', 7),
    ('Consistency and Cross-Validation', 8)
ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.rules
    ADD COLUMN IF NOT EXISTS check_category text;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'rules_check_category_fkey'
    ) THEN
        ALTER TABLE public.rules
            ADD CONSTRAINT rules_check_category_fkey
            FOREIGN KEY (check_category)
            REFERENCES public.rule_check_categories (name)
            ON UPDATE CASCADE
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_rules_check_category
    ON public.rules (check_category);

COMMENT ON COLUMN public.rules.check_category IS
    'Name of the rule_check_categories entry this rule is grouped under in analysis results; NULL = uncategorized.';

COMMIT;

-- Verify:
--   SELECT name, sort_order FROM public.rule_check_categories ORDER BY sort_order;
--   SELECT column_name FROM information_schema.columns
--    WHERE table_schema='public' AND table_name='rules' AND column_name='check_category';
